### ISSUE TITLE
ORC file issues

### ISSUE THREAD

**Issue by davesrocketshop** [dbcook/openrocket-database#11]
Sorry but I have a few more. This should be the last of it though. If you have a different method you prefer for reporting these issues just let me know. Also, love that you're doing this. I know it's not a trivial effort.

semroc:

    <NoseCone>
      <Manufacturer>SEMROC</Manufacturer>
      <PartNumber>BNC-30C</PartNumber>
      <Description>Nose cone, balsa, BNC-30C, 0.75", spherical</Description>
      <Material Type="BULK">Balsa, bulk, 7lb/ft3</Material>
      <Filled>true</Filled>
      <Shape>ELLIPSOID</Shape>
      <OutsideDiameter Unit="in">0.0.767</OutsideDiameter> - 0.0. multiple occurences
      <ShoulderDiameter Unit="in">0.723</ShoulderDiameter>
      <ShoulderLength Unit="in">0.375</ShoulderLength>
      <Length Unit="in">0.75</Length>
    </NoseCone>

	interchanging "SEMROC" and "Semroc" for manufacturer name
	
	"Balsa, bulk, 7 kg/m3" material specified instead of "Balsa, bulk, 7 lb/ft3", or material is not specified
	
quest

	Material "Polystyrene, cast, bulk" defined but "Polystyrene, bulk" used
	Material "Paper, spiral kraft glassine, Estes avg, bulk" but "Paper" used for some body tubes
	Material "Fiber, bulk" but "Paper" used for some centering rings

competition chutes

	Material "Mylar polyester film, 0.50 mil" but "Mylar polyester film, 0.5 mil" used

bluetube

    <Materials>
        
        <Material UnitsOfMeasure="g/cm3">
            <Name>Vulcanized Fiber</Name>
            <Density>1153.5</Density>
            <Type>BULK</Type>
        </Material>
    </Materials> -- too early
        <Material UnitsOfMeasure="g/cm3">
            <Name>Plywood, aircraft, 1/4 in. bulk</Name>
            <Density>344.3</Density>
            <Type>BULK</Type>
       </Material>

	No material definition for "Plywood, aircraft, 1/2 in. bulk"

**Comment by dbcook** [comment]
Thanks!  I'll have a look at these, though probably not quite as quick as the last batch since we're into the work week.

This is by far the best way to report problems; I get an email when a GitHub issue is created.

**Comment by dbcook** [comment]
Notes on the fixes:
semroc - I did not find any more "0.0." occurrences, they got fixed in 0.9.3.3
semroc - changed all "Semroc" manufacturer names to "SEMROC", about 1/3 of the total.  I don't think this has any actual effect except making the UI listings look consistent.
semroc - there were 202 "Balsa, bulk, 7 kg/m3" entries...would all have had zero mass. Big catch there.
bluetube - in addition to fixing the broken plywood refs, I noticed that the actual density value was for lite-ply (and has been that way for a long time I think).  The ARR website now specifies Baltic birch, which is about 2x the density.  Adopted the Baltic birch value.
quest - various parts will now have mass

**Comment by dbcook** [comment]
I should mention that to get this update you need to install your parts database from this GitHub repo.  I don't know when the OpenRocket devs will roll it into the beta releases.

**Comment by davesrocketshop** [comment]
No problem. I link to your repo from mine (https://github.com/davesrocketshop/Rocket)

This is the Rocket Workbench for FreeCAD. Thanks for the quick turnaround. I know even easy fixes take time when multiplied over many occurences
