### ISSUE TITLE
BMS - Thickness of CR5060-W

### ISSUE THREAD

**Issue by ghost** [dbcook/openrocket-database#13]
Thickness of CR5060-W should be 0.125 NOT 0.05. Balsa Machining part

**Comment by dbcook** [comment]
Sounds like a plausible error but where are you seeing this?  I've not included a BMS file in my database (yet) due to a bunch of missing manufacturer specs for various balsa parts.  If you're looking in the old 15.03 parts source code, none of that code has been carried forward to the new release directly.

**Comment by ghost** [comment]
According to OR this is not legacy
![centeringRings1](https://user-images.githubusercontent.com/53155232/189723061-ec79060f-90f5-4c43-9938-3ca00bcf94bc.png)

**Comment by dbcook** [comment]
The non-legacy indicator looks to be an OR bug as described in openrocket#1668

**Comment by ghost** [comment]
Dave, I would be glad to help in your effort if you would get in contact with me! Including adding new parts.

**Comment by dbcook** [comment]
Update on BMS - I've left Bill Saindon a voicemail about filling in parts info gaps after my email got spam-bounced from his mail agent.

**Comment by ghost** [comment]
BMS.ORC file created
