### ISSUE TITLE
No LOC centering rings 

### ISSUE THREAD

**Issue by ghost** [dbcook/openrocket-database#15]
No LOC centering rings are in this database.

**Comment by dbcook** [comment]
I need to check up on that; might be due to formerly missing data. The LOC
website has improved lately and we might be able to make updates.

Dave

**Comment by dbcook** [comment]
I check on this tonight, they are indeed not there.  The reason is that when I made the LOC file back in 2018, a majority of the thicknesses were not specified, leaving the mass uncertain by a factor of two.

I reviewed the LOC website today and they now list thicknesses for all of their own brand rings and bulkheads.  However the only thing they say about the material is "wood" and weights are not given.  The photos appear to show (but not definitively) that they are plywood, but we need a statement from them about whether they are baltic birch or lite-ply, since there is a ~2x difference in density.  With that information we can go ahead and add them to the loc_precision file.

Things are different for the Public Missiles brand rings, where LOC states that centering rings and bulk plates for 3.9" and smaller tubes are 1/4" birch plywood...I rather doubt that the very small sizes for 2.1" tubes etc. are really 1/4" thick - possible but unlikely.

There is a decision about whether to move the PML parts into the LOC file due to the acquisition.  I am tentatively thinking to leave them in the separate PML file, on the premise that it's more likely than not that LOC will discontinue the redundant PML sizes when they exhaust existing stock acquired at the merger.

**Comment by dbcook** [comment]
Update - I have sent an email inquiry to LOC.

**Comment by ghost** [comment]
I would leave the PML in a separate file. That way when they are gone , you just delete the file


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by dbcook** [comment]
This email to me from one of the owners of LOC Precision confirms authoritatively that the LOC branded wood centering rings are Baltic birch:
[begin snippet]
They Are Baltic birch.

Thickness depends on a few factors such as the distance between OD and ID.  Smaller distance (2.2x 38mm) are ¼” Actually measured as 6mm.  And a 2.2”x29mm is 3mm wood. Same goes for the 1.9” and 1.6” diameters.

If you have a spreadsheet to share it might make it easier if I help just fill it in?

Cheers!

David Barber
435 Factory St.
STE A
Plymouth, WI 53073
920-892-0557
[end snippet]

**Comment by ghost** [comment]
Did you mention that you knew someone connected to the BMS website? They don’t give weights or materials listed. I can probably assume balsa but I don’t know.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by dbcook** [comment]
I do know Bill Saindon and am trying to reach him.  His hosting mail server
is rejecting gmail as spam so I'm going to leave a voicemail.

-Dave

**Comment by dbcook** [comment]
Just a note to document that I've started inserting the LOC plywood centering rings.  Stephan and I have decided not to do the cluster mount rings for now since OR doesn't know how to compute the mass and moments of inertia for the cluster cutout geometries.

**Comment by dbcook** [comment]
The LOC brand plywood centering rings are all incorporate in loc_precision.orc now and merged to master.  Closing this issue.  The other one about various missing LOC data remains open.
