### ISSUE TITLE
LOC Parachutes 

### ISSUE THREAD

**Issue by ghost** [dbcook/openrocket-database#21]
LOC Parachutes in database do not line up with what is currently available on LOC website.

**Comment by dbcook** [comment]
That is definitely possible.  Once upon a time LOC parachutes were handmade by Deb Schulz.  If you have a look at the file history on github you can see when I last captured the product info.

Normally when parts are superseded I will leave the original entries so that people can clone old versions of rockets.  If the part design changes but the PN or SKU is kept the same, my practice would be to add a suffix to the old superseded PN indicating it's obsolete.  That has not happened very often; usual manufacturing practice is to change the PN if a significant change is made to the design.

There is a big complication:

Lately I've seen manufacturers including LOC no longer using PNs at all; modern e-shop software doesn't make you display a PN for a product; only a description is shown to the client.  But the OR parts system was built around something of an assumption that there would be a PN...I haven't worked through things to see how well it would work if we just encoded version information in the description, or took over the PN for versioning of parts without a manufacturer's PN.

Without PNs, matching parts to their use in kits also becomes very difficult.

**Comment by dbcook** [comment]
Added 2022 parachute lineup to loc_precision.orc.  Appended "-2022" to PNs following the old pattern of LP-xx since LOC no longer gives PNs on the website.
