### ISSUE TITLE
LOC/Precision parachute duplication and inclusion of year in part number/description

### ISSUE THREAD

**Issue by hcraigmiller** [dbcook/openrocket-database#23]
Two questions:

1. Are these parachutes duplicated?
2. Is there a reason that the year is being included in the part number or part description?

![Parachutes Duplicates](https://user-images.githubusercontent.com/68821492/197316694-d390db1e-9d04-4705-8953-a60689d17217.png)

**Comment by dbcook** [comment]
They are different.  In 2018 the material was specified as 1.7oz.  In 2022
it is specified as 1.9oz and the photos show distinctly different
construction, and the number of shroud lines has changed for some sizes.
Also the new lineup adds some new sizes not previously offered.

-Dave

**Comment by dbcook** [comment]
Forgot to mention in the previous comment that on the 2022 website, all PNs
have disappeared.  There is some commentary in the .orc file about that
situation and the need to generate synthetic PNs so we don't have blanks.
Long term that's a big problem because newer vendors that arise within the
e-commerce world may never have PNs.

**Comment by hcraigmiller** [comment]
The option that I have been using is to generate part numbers that are then approved by the vendor. So far, the vendors have been very open to this process.
