### ISSUE TITLE
Question regarding the duplication created by listing resellers as manufacturers of components

### ISSUE THREAD

**Issue by hcraigmiller** [dbcook/openrocket-database#27]
Is there a reason that resellers are being listed as component manufacturers? For example, the most recent release contains parachutes that have Rocketarium as the "manufacturer" (Crossfire parachutes) when the Rocketarium website identifies Top Flight Recovery as the actual manufacturer; the same parachute is listed a second time with Top Flight Recovery as the manufacturer (**two listings for the same, _identical_ component**).

Listing resellers as component manufacturers is not only misleading, obscuring the true identity of the component manufacturer (and diminishing the manufacturer's contribution to the field), but it also creates unnecessary duplication for users to weed through when selecting components in OpenRocket. Is there a reason for this type of duplication that I am missing?

**Comment by dbcook** [comment]
Hi Craig,

There is quite a bit of complexity around those issues.  The Rocketarium
file and research was provided by Stephen (cc'd) so I can't comment on the
specifics of that one.

Generally I haven't listed parts where a vendor is OEM'ing parts from
another vendor *and* that sourcing is publicly acknowledged by the vendor
*and* the part numbers match, i.e.  it's a straight reseller situation.
Thus far I've not taken the approach that we will list the entire catalog
of each vendor, whether the parts are original or resale. More than one
person has explicitly asked for that, but I don't want to do it because of
the large amount of additional work involved.

However, there are several situations where I list parts for a vendor even
if I personally know they are a resale item

   - If the vendor uses a PN/SKU that differs from the upstream supplier's
   PN
   - If the OEM relationship is not publicly disclosed (the average user
   would have no way of knowing)
   - If the vendor is known or believed to be modifying or enhancing the
   parts
   - If the vendor has a large stock of older items that don't match
   current upstream production
   - If the upstream vendor is not in the sport rocketry ecosystem

Then there's the fun with recent mergers and acquisitions., like PML -->
LOC.  For now we are leaving the PML parts in the PML file until we see
what LOC does with the product line.  It doesn't help that LOC has stopped
using PNs.

Hope this sheds some light.  It sounds like we should have a look through
the Rocketarium file and pull items that are acknowledged resale.

Dave

**Comment by hcraigmiller** [comment]
Following the criterion stated above, the following Rocketarium parachutes should be removed from the database (identified by part number):
CF-24
CF-30
CF-36
CF-48
CF-60
CF-78
PAR-18
PAR-24
PAR-30
PAR-36
PAR-48
PAR-54
These are manufactured by Top Flight Recovery and appear elsewhere in the database.

Following the criterion stated above, all of the Rocketarium **_nylon_** parachutes should be **_relabeled_** as manufactured by Top Flight Recovery; these are Top Flight Recovery parachutes that **_do not_** appear elsewhere in the database.

Rocketarium does manufacture a 12", 15" and 18" plastic parachute, that appear in the database, but it's mylar parachutes are absent.

There is one file that appears to be in error, see below, and this should be resolved (one file needs to be deleted).

![Parachutes](https://user-images.githubusercontent.com/68821492/206357722-a4714cd5-705a-4728-96a1-7a5d2aa8bc64.png)

**Comment by hcraigmiller** [comment]
Following the criterion stated above, all of the Rocketarium **_nylon_** streamers should be **_relabeled_** as manufactured by Top Flight Recovery; these are Top Flight Recovery streamers that **_do not_** appear elsewhere in the database.

**Comment by dbcook** [comment]
There is already a top_flight file that just has parachutes; the streamers
ought to be moved in there.  All the parachutes you mentioned (and some
larger sizes too) are already there.

-Dave

**Comment by hcraigmiller** [comment]
I'm just looking at the OpenRocket parts library as it is displayed to users. I didn't look to see from what file that data is coming from. 

Based upon what you have indicated, all of the Rocketarium nylon parachutes should be moved to the top_flight file with Top Flight Recovery put as the manufacturer; same for the streamers identified.

**Comment by dbcook** [comment]
It was even more than that :). In addition to the Top Flight stuff there
were PML conical chutes, phenolic tubes, and phenolic couplers.  I just
pushed a new master with v 1.0.0.2 that takes care of all that.  The PML
file got a few additions with the discovery of the full length coupler
listings in the Rocketarium file that were confirmed on the PML site in the
wayback machine.

Rocketarium also list the Aerotech 1.9 tube, but I've left that in because
there is no Aerotech file, though Semroc/eRockets has an exact equivalent
that they sourced themselves.

-Dave
